### ISSUE TITLE
No need to delay

### ISSUE THREAD

**Issue by VesaKarvonen** [Hopac/Hopac.Extras#3]
Looking at [IO.fs](https://github.com/Hopac/Hopac.Extras/blob/master/src/Hopac.Extras/IO.fs#L106), the following pattern works:

```fsharp
          /// Creates a job that disposes the file.
          Close: unit -> Job<unit> }
        interface IAsyncDisposable with
            member x.DisposeAsync() = Job.delay x.Close
```

```fsharp
          Close = fun _ -> IVar.tryFill close () }
```

But it is safe to simplify that to:

```fsharp
          /// Creates a job that disposes the file.
          Close: unit -> Job<unit> }
        interface IAsyncDisposable with
            member x.DisposeAsync() = x.Close()
```

```fsharp
          Close = IVar.tryFill close }
```

Or even to:

```fsharp
          /// A job that disposes the file.
          Close: Job<unit> }
        interface IAsyncDisposable with
            member x.DisposeAsync() = x.Close
```

```fsharp
          Close = IVar.tryFill close () }
```

(This also changes the type of Close.)

Functions in Hopac that return `Job<_>` or `Alt<_>` objects generally do not immediately perform any effects.  To perform the effects (such as trying to fill the ivar) the returned job or alt needs to be executed.  So, there is no semantic need to delay the construction of the job.

The `IAsyncDisposable` interface allows lazy creation of the dispose job, so that it need not be preallocated.  The comment to not perform the disposal immediately is to warn against patterns like

```fsharp
  override this.DisposeAsync () = this.CloseFlag <- true ; Job.unit ()
```

which would not work as expected.  I should eloborate this on the `IAsyncDisposable` reference docs.

**Addition:** See documentation of [DisposeAsync](http://hopac.github.io/Hopac/Hopac.html#def:abstract%20Hopac.IAsyncDisposable.DisposeAsync).

**Comment by vasily-kirichenko** [comment]
Thanks! Fixed in https://github.com/Hopac/Hopac.Extras/commit/160bbd89a66723c1998684b11ba4fd8b98ed10d8

I added the delays when I discovered early file closes in `Job.usingAsync`. `DisposeAsync` at that time looked like this:
```fsharp
 Close: unit -> Job<unit> }
    interface IAsyncDisposable with
        member x.DisposeAsync() = 
            printfn "Closing file..."
            x.Close()
```
So I added `Job.delay` to make it lazy. Anyway, now I understand what was the original problem.
